# Generated by Django 4.0.4 on 2022-04-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_delete_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderitem',
            new_name='Orderi',
        ),
    ]
