# Generated by Django 4.0.4 on 2022-04-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_orderitem_orderi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderi',
            new_name='Orderitem',
        ),
    ]
