# Generated by Django 4.0.4 on 2022-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
